/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SellRouteImport } from './routes/sell'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MeRouteImport } from './routes/me'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PIdRouteImport } from './routes/p.$id'
import { Route as MPidPeerRouteImport } from './routes/m.$pid.$peer'

const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PIdRoute = PIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MPidPeerRoute = MPidPeerRouteImport.update({
  id: '/m/$pid/$peer',
  path: '/m/$pid/$peer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/messages': typeof MessagesRoute
  '/orders': typeof OrdersRoute
  '/sales': typeof SalesRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/sell': typeof SellRoute
  '/p/$id': typeof PIdRoute
  '/m/$pid/$peer': typeof MPidPeerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/messages': typeof MessagesRoute
  '/orders': typeof OrdersRoute
  '/sales': typeof SalesRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/sell': typeof SellRoute
  '/p/$id': typeof PIdRoute
  '/m/$pid/$peer': typeof MPidPeerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/messages': typeof MessagesRoute
  '/orders': typeof OrdersRoute
  '/sales': typeof SalesRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/sell': typeof SellRoute
  '/p/$id': typeof PIdRoute
  '/m/$pid/$peer': typeof MPidPeerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/me'
    | '/messages'
    | '/orders'
    | '/sales'
    | '/saved'
    | '/search'
    | '/sell'
    | '/p/$id'
    | '/m/$pid/$peer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/me'
    | '/messages'
    | '/orders'
    | '/sales'
    | '/saved'
    | '/search'
    | '/sell'
    | '/p/$id'
    | '/m/$pid/$peer'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/me'
    | '/messages'
    | '/orders'
    | '/sales'
    | '/saved'
    | '/search'
    | '/sell'
    | '/p/$id'
    | '/m/$pid/$peer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MeRoute: typeof MeRoute
  MessagesRoute: typeof MessagesRoute
  OrdersRoute: typeof OrdersRoute
  SalesRoute: typeof SalesRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  SellRoute: typeof SellRoute
  PIdRoute: typeof PIdRoute
  MPidPeerRoute: typeof MPidPeerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$id': {
      id: '/p/$id'
      path: '/p/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof PIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$pid/$peer': {
      id: '/m/$pid/$peer'
      path: '/m/$pid/$peer'
      fullPath: '/m/$pid/$peer'
      preLoaderRoute: typeof MPidPeerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MeRoute: MeRoute,
  MessagesRoute: MessagesRoute,
  OrdersRoute: OrdersRoute,
  SalesRoute: SalesRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  SellRoute: SellRoute,
  PIdRoute: PIdRoute,
  MPidPeerRoute: MPidPeerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
